<?php

declare(strict_types=1);

namespace Dbp\Relay\BasePublicationConnectorPureBundle\EventSubscriber;

use Dbp\Relay\BasePublicationConnectorPureBundle\Event\PublicationPostEvent;
use Dbp\Relay\BasePublicationConnectorPureBundle\Event\PublicationPreEvent;
use Dbp\Relay\CoreBundle\LocalData\AbstractLocalDataEventSubscriber;
use Dbp\Relay\CoreBundle\LocalData\LocalDataPostEvent;
use Dbp\Relay\CoreBundle\Rest\Options;

class PublicationLocalDataEventSubscriber extends AbstractLocalDataEventSubscriber
{
    private const CATEGORY_NAME_SOURCE_ATTRIBUTE = 'categoryName';

    public static function getSubscribedEventNames(): array
    {
        return [
            PublicationPreEvent::class,
            PublicationPostEvent::class,
        ];
    }

    protected function getAttributeValue(LocalDataPostEvent $postEvent, array $attributeMapEntry): mixed
    {
        $sourceData = $postEvent->getSourceData();
        $options = $postEvent->getOptions();

        switch ($attributeMapEntry[self::SOURCE_ATTRIBUTE_KEY]) {
            case self::CATEGORY_NAME_SOURCE_ATTRIBUTE:
                return $sourceData['category']['term'][self::getPureLanguageTag($options)] ?? null;
        }

        return parent::getAttributeValue($postEvent, $attributeMapEntry); // TODO: Change the autogenerated stub
    }

    private static function getPureLanguageTag(array $options): string
    {
        return match (Options::getLanguage($options) ?? 'de') {
            'en' => 'en_GB',
            default => 'de_DE',
        };
    }
}
